language: node_js
node_js:
    - 10
install: yarn install
script: yarn build

deploy:
    - provider: pages
      repo: stanvishne/fsm-demo
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: build
      on:
          branch: master
